spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.104:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.0.104
    port: 6379


server:
  context-path: /sell

#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.hins.sell.LoggerTest: debug

wechat:
  mpAppidHins:  wx7c91575fba9b5f9d
  mpAppSecretHins: a767895c00ec4d4e743df548a2e1f03b
  mpAppid:  wxc2c21e60d0bf85a5
  mpAppSecret: ce456cbf7a9e7a913cbf289a14ab69cd
  openAppid: wxc2c21e60d0bf85a5
  openAppSecret: 397d811fcc2c8e3f3e5f23071b3957a0
  mchId: 1336674701
  mchKey: iSoftStoneiSoftStoneiSoftStone32
  keyPath: /var/wechat_cert/h5.p12
  notifyUrl: http://hins.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: gWn_cKI3Ifwn62v-87RP6CsleBY2TDyfsE-Hiz0AWuM

projectUrl:
  wechatMpAuthorize: http://hins.natapp4.cc
  wechatOpenAuthorize: http://hins.natapp4.cc
  sell: http://hins.natapp4.cc