spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.104:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.0.104
    port: 6379


server:
  context-path: /sell

#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.hins.sell.LoggerTest: debug

wechat:
  mpAppidHins:  wx7c91575fxxxxxx
  mpAppSecretHins: a767895c00ecxxxxxxxx
  mpAppid:  wxc2c21e60xxxxxx
  mpAppSecret: ce456cbf7a9e7a913cxxxxxx
  openAppid: wxc2c21exxxxxx
  openAppSecret: 397d811fcc2c8e3f3exxxxxx
  mchId: 13xxxxx
  mchKey: xxxxxxxxx
  keyPath: /var/wechat_cert/h5.p12
  notifyUrl: http://hins.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: gWn_cKI3Ifwn62v-87RP6Cxxxxxx

projectUrl:
  wechatMpAuthorize: http://hins.natapp4.cc
  wechatOpenAuthorize: http://hins.natapp4.cc
  sell: http://hins.natapp4.cc
